brews:
  - name: pluto
    github:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Detect deprecated Kubernetes apiVersions
    test: |
      system "#{bin}/pluto version"
