brews:
  - name: pluto
    github:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Detect deprecated Kubernetes apiVersions
    test: |
      system "#{bin}/pluto version"
builds:
  - ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goos:
      - linux
      - darwin
    goarm:
      - 6
      - 7
