brews:
  - name: pluto
    goarm: 6
    repository:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Detect deprecated Kubernetes apiVersions
    test: |
      system "#{bin}/pluto version"
release:
  prerelease: auto
  footer: |
    You can verify the signatures of both the checksums.txt file and the published docker images using [cosign](https://github.com/sigstore/cosign).

    cosign 1.x
    ```
    cosign verify-blob checksums.txt --signature=checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub
    ```

    cosign 2.x
    ```
    cosign verify-blob checksums.txt --signature=checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub --insecure-ignore-tlog
    ```

    ```
    cosign verify us-docker.pkg.dev/fairwinds-ops/oss/pluto:v5 --key https://artifacts.fairwinds.com/cosign.pub
    ```
builds:
  - ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    main: cmd/pluto/main.go
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarm:
      - 6
      - 7
checksum:
  name_template: "checksums.txt"

signs:
- cmd: cosign
  args: ["sign-blob", "--key=hashivault://cosign", "--output-signature=${signature}", "${artifact}"]
  artifacts: checksum

docker_signs:
- artifacts: all
  args: ["sign", "--key=hashivault://cosign", "${artifact}", "-r"]

dockers:
- image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}-armv7"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}-armv7"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}-armv7"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
docker_manifests:
- name_template: us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}
  image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:{{ .Tag }}-armv7"
- name_template: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}
  image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}-armv7"
- name_template: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}-amd64"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "us-docker.pkg.dev/fairwinds-ops/oss/pluto:v{{ .Major }}.{{ .Minor }}-armv7"
