brews:
  - name: pluto
    goarm: 6
    tap:
      owner: FairwindsOps
      name: homebrew-tap
    folder: Formula
    description: Detect deprecated Kubernetes apiVersions
    test: |
      system "#{bin}/pluto version"
release:
  prerelease: auto
builds:
  - ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarm:
      - 6
      - 7
dockers:
- image_templates:
  - "quay.io/fairwinds/pluto:{{ .Tag }}-amd64"
  - "quay.io/fairwinds/pluto:v{{ .Major }}-amd64"
  - "quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}-amd64"
  use_buildx: true
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/fairwinds/pluto:{{ .Tag }}-arm64v8"
  - "quay.io/fairwinds/pluto:v{{ .Major }}-arm64v8"
  - "quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}-arm64v8"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "quay.io/fairwinds/pluto:{{ .Tag }}-armv7"
  - "quay.io/fairwinds/pluto:v{{ .Major }}-armv7"
  - "quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}-armv7"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
docker_manifests:
- name_template: quay.io/fairwinds/pluto:{{ .Tag }}
  image_templates:
  - "quay.io/fairwinds/pluto:{{ .Tag }}-amd64"
  - "quay.io/fairwinds/pluto:{{ .Tag }}-arm64v8"
  - "quay.io/fairwinds/pluto:{{ .Tag }}-armv7"
- name_template: quay.io/fairwinds/pluto:v{{ .Major }}
  image_templates:
  - "quay.io/fairwinds/pluto:v{{ .Major }}-amd64"
  - "quay.io/fairwinds/pluto:v{{ .Major }}-arm64v8"
  - "quay.io/fairwinds/pluto:v{{ .Major }}-armv7"
- name_template: quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}-amd64"
  - "quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "quay.io/fairwinds/pluto:v{{ .Major }}.{{ .Minor }}-armv7"
