name: "Download pluto binary"
description: "Downloads the pluto binary by pulling the container image"
inputs:
  IMAGE_PULL_URL:
    description: "pull url for container image, i.e.: quay.io/fairwinds/pluto"
    default: "quay.io/fairwinds/pluto"
    required: true
  IMAGE_TAG:
    description: "tag for container image, i.e.: v5"
    default: "v5"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download pluto binary
      shell: bash
      run: |
        podman pull ${{ inputs.IMAGE_PULL_URL }}:${{ inputs.IMAGE_TAG }}
        podman cp $(podman create --rm ${{ inputs.IMAGE_PULL_URL }}:${{ inputs.IMAGE_TAG }}):/pluto /usr/local/bin/pluto

        pluto --help